---
# tasks file for baseline

# - name: Upgrade all apt packages
#   apt: upgrade=dist force_apt_get=yes
#   become: yes

- name: install requirements for bluetooth headers and python depenencies
  apt:
    name:
      - python3
      - libbluetooth-dev
      - build-essential
      - libglib2.0-dev
      - python3-pip
      - libglib2.0-dev
      - glib2-devel
      - libboost-all-dev
      - libboost-python1.62-dev
      
    state: latest
    update_cache: yes  
  become: yes

